name: Generate per-folder READMEs

on:
  pull_request:
    paths:
      - '.github/copilot-instructions/**'
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
      - name: Run generator
        env:
          FAIL_ON_VALIDATION: '1'
        run: |
          python .github/copilot-instructions/scripts/generate_readmes.py .github/copilot-instructions
      - name: Check for changes
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            echo "Generated READMEs or index changed. Please run the generator locally and include the changes in your PR.";
            git --no-pager diff || true
            exit 1
          fi
